export const Crypto = {
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "USDT": "Tether",
    "BNB": "Binance Coin",
    "ADA": "Cardano",
    "XRP": "XRP",
    "USDC": "USD Coin",
    "DOGE": "Dogecoin",
    "DOT": "Polkadot",
    "BUSD": "Binance USD",
    "UNI": "Uniswap",
    "BCH": "Bitcoin Cash",
    "LTC": "Litecoin",
    "SOL": "Solana",
    "LINK": "Chainlink",
    "MATIC": "Polygon",
    "THETA": "THETA",
    "XLM": "Stellar",
    "ETC": "Ethereum Classic",
    "VET": "VeChain",
    "WBTC": "Wrapped Bitcoin",
    "FIL": "Filecoin",
    "TRX": "TRON",
    "EOS": "EOS",
    "AAVE": "Aave",
    "XMR": "Monero",
    "NEO": "NEO",
    "ATOM": "Cosmos",
    "XTZ": "Tezos",
    "ALGO": "Algorand",
    "MKR": "Maker",
    "KSM": "Kusama",
    "CRO": "Crypto.com Coin",
    "LEO": "UNUS SED LEO",
    "AVAX": "Avalanche",
    "DASH": "Dash",
    "HBAR": "Hedera Hashgraph",
    "DCR": "Decred",
    "RUNE": "THORChain",
    "CEL": "Celsius",
    "SNX": "Synthetix",
    "BTT": "BitTorrent",
    "ZEC": "Zcash",
    "SUSHI": "SushiSwap",
    "EGLD": "Elrond",
    "MANA": "Decentraland",
    "ONT": "Ontology",
    "NEAR": "NEAR Protocol",
    "HNT": "Helium",
    "ZIL": "Zilliqa",
    "UMA": "UMA",
    "BTG": "Bitcoin Gold",
    "QTUM": "Qtum",
    "ICX": "ICON",
    "BAT": "Basic Attention Token",
    "FTT": "FTX Token",
    "WAVES": "Waves",
    "CHZ": "Chiliz",
    "COMP": "Compound",
    "ENJ": "Enjin Coin",
    "ZEN": "Horizen",
    "NEXO": "Nexo",
    "DGB": "DigiByte",
    "OMG": "OMG Network",
    "RVN": "Ravencoin",
    "ONE": "Harmony",
    "SC": "Siacoin",
    "HOT": "Holo",
    "KCS": "KuCoin Token",
    "LSK": "Lisk",
    "ZRX": "0x",
    "STX": "Stacks",
    "YFI": "yearn.finance",
    "XEM": "NEM",
    "BNT": "Bancor",
    "XDC": "XDC Network",
    "REV": "Revain",
    "FLOW": "Flow",
    "TFUEL": "Theta Fuel",
    "GRT": "The Graph",
    "NANO": "Nano",
}