const Page = ({ params, }: {
    params: { slug: string; };
}) => {
    const [device, setDevice] = useState("desktop");
    const [transaction, setTransaction] = useState([]);
    const [balance, setBalance] = useState("0");
    useEffect(() => {
        const handleResize = () => {
            if (window.innerWidth < 768) {
                setDevice("mobile");
            }
            else if (window.innerWidth < 1024) {
                setDevice("tablet");
            }
            else {
                setDevice("desktop");
            }
        };
        handleResize();
    }, []);
    const getTransactions = async () => {
        const response = await axios.get(`/api/detail?address=${params.slug}&page=1&perPage=50`);
        const responseConvert = response.data;
        setTransaction(responseConvert.sellTransaction.map(transaction => {
            return {
                from: transaction?.from || "",
                balance: responseConvert.walletBalance,
                buyPrice: transaction?.buyPrice || "10000",
                sellPrice: transaction?.sellPrice || "1000",
                timeStamp: transaction?.timeStamp || new Date().getTime(),
                value: transaction?.value || "1000",
            };
        }));
        setBalance(responseConvert.walletBalance);
    };
    useEffect(() => {
        getTransactions();
    }, []);
    return (<>
      <Head>
        <title>Contract</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen py-2">
        <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
          <h1 className="text-6xl font-bold">
            Contract
          </h1>
          <p className="mt-3 text-2xl">
            <code className="p-3 font-mono text-lg bg-gray-100 rounded-md">
              {params.slug}
            </code>
          </p>
          <div className="flex flex-col items-center justify-center min-h-screen py-2">
            <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
              <h1 className="text-6xl font-bold">
                Contract
              </h1>
              <p className="mt-3 text-2xl">
                <code className="p-3 font-mono text-lg bg-gray-100 rounded-md">
                  {params.slug}
                </code>
                </p>
                <div className="flex flex-col items-center justify-center min-h-screen py-2">
                  <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                    <h1 className="text-6xl font-bold">
                      Contract
                    </h1>
                    <p className="mt-3 text-2xl">
                      <code className="p-3 font-mono text-lg bg-gray-100 rounded-md">
                        {params.slug}
                      </code>
                    </p>
                  </main>
                </div>
                </main>
                </div>
                </main>
                </div>
                </>);

}